### ISSUE TITLE
Provide dynamically linked libraries

### ISSUE THREAD

**Issue by Namaneo** [matoya/libmatoya#25]
Hi,

I just discovered libmatoya, the project looks truly awesome!

I decided to give it a try and, as a C# developer, I wanted to create bindings for .NET Core... to discover that .NET does not support static library linking at all. Could it be considered to provide builds of dynamically linked libraries as well, or is it technically impossible?

Side note: it's been a while since I've played with C/C++ projects, I hope what I ask makes sense. 🙂 

Thanks!

**Comment by chrisd1100** [comment]
It actually should be pretty easy to build a DLL out of it if you take the static lib and header, include the header in a dummy .c file, and compile it / link it with `-DMTY_EXPORT -dll` options. When I have time I'll try to put together a demo.

**Comment by Namaneo** [comment]
Just created a PR to add this ability, thanks to your advice. Closing this issue. :slightly_smiling_face: 

Btw, feel free to decline it (or even any other I opened): I can understand this library aims to be as clean and light as possible. If someone come across with the same ideas, some resources will still be available in the PR history!

**Comment by renenucci** [comment]
> Just created a PR to add this ability, thanks to your advice. Closing this issue. 🙂
> 
> Btw, feel free to decline it (or even any other I opened): I can understand this library aims to be as clean and light as possible. If someone come across with the same ideas, some resources will still be available in the PR history!

Hi, I'm in very similar usecase that yours (C# developer that has been a long time since I've played with C/C++), I've searched for that PR but only found this one : https://github.com/snowcone-ltd/libmatoya/pull/41 

Is that correct? I tried change "makefile", but dont know how to call to generates DLL (then use as pInvoke in C#).

I tried "nmake" but it generates .lib file only
