### ISSUE TITLE
Mid-frame key events / imgui

### ISSUE THREAD

**Issue by chadmortimer** [matoya/libmatoya#34]
Due to the asynchronous nature of my libmatoya app (with separate event, render, app threads) I am running into an issue where imgui is asserting with a mismatch on io.XXX vs io.KeyMods  occasionally when releasing modifier keys (for app shortcuts) - presumably due to the fact that this could happen mid-frame.

What would be the suggested way of dealing with this? So far I am looking at queuing the events and submitting them to imgui in the render thread prior to creating a new frame. Would this approach make sense?

**Comment by chrisd1100** [comment]
Yes in a multithreaded scenario, you should queue up the `MTY_Event`s to your render thread and apply them to ImGui's IO singleton just before rendering. ImGui holds state in a global context and you need to take care when calling any ImGui function from multiple threads.

I'm interested in your use-case, I would love some more detailed feedback if you're willing to have a longer conversation. If so email me at cdd@matoya.group!

**Comment by chadmortimer** [comment]
Will definitely do so.

In terms of queuing up the events, would an MTY_List suit the need? By pushing events to the list as they occur and then from the render thread just empty the list starting at the first element (so that the event sequence is preserved), removing each item until empty (or perhaps up to predefined max to avoid holding up the rendering?). Although I would need to possible keep track of the length of the list myself as there doesn't seem to be a "MTY_ListGetSize" or similar? I would probably only want to quickly process the number of events available in the list at the start of the render loop, anything added in the meanwhile / above the predefined max will be handled in the next iteration then...

**Comment by chrisd1100** [comment]
The `MTY_Queue` will work well for this. It's an efficient, thread safe, semi-lock free queue with statically allocated buffers, but probably a max of 100 elements of size `sizeof(MTY_Event)` will do the trick. Before rendering you pop everything off the queue in a loop and modify your ImGui IO.

You can find examples of a lot of this in my libretro front-end Merton: https://github.com/matoya/merton/tree/master/src

**Comment by chadmortimer** [comment]
Fantastic. The examples will be most helpful!

I wish I had seen it earlier. I’ve spent quite some time working on the imgui bindings

On 06 Jun 2021, at 20:34, Christopher D. Dickson ***@***.***> wrote:

﻿

The MTY_Queue will work well for this. It's an efficient, thread safe, semi-lock free queue with statically allocated buffers, but probably a max of 100 elements of size sizeof(MTY_Event) will do the trick. Before rendering you pop everything off the queue in a loop and modify your ImGui IO.

You can find examples of a lot of this in my libretro front-end Merton: https://github.com/matoya/merton/tree/master/src
